# Data Preparation

While the data scrapper gets the data related to the instagram users, we are using two datasets from Kaggle with small variations to recreate how the algorithm will work with real data.

In [144]:
# Import libraries
import pandas as pd
import numpy as np
import ast

In [145]:
# Upload companies dataset
df_co = pd.read_csv('brands_df.csv')
df_co

,brand_name,brand_name.1,brand_description,brand_likes,brand_post_description,all_descriptions,descriptions_translated,hashtags,category,hashtags_translated,followers,location
0,abcnetwork,abcnetwork,ABC\nAmerica‚Äôs Network.\nabc.com,1871.40,Who will make Top 24!? Tune in to #AmericanIdo...,ABC\nAmerica‚Äôs Network.\nabc.com Who will make...,ABC\nAmerica‚Äôs Network.\nabc.com Who will make...,"['americanidol', 'americanidol', 'americanidol...",social,"['americanidol', 'americanidol', 'americanidol...",4172512,Pakistan
1,acerojoaquintorres,acerojoaquintorres,Joaquin Torres\nArchitectural designer\nA-cero...,1504.80,"Esta es, sin duda, una de las viviendas m√°s gr...",Joaquin Torres\nArchitectural designer\nA-cero...,Joaquin Torres\nArchitectural Designer\nSteel\...,"['sitevisit', 'luxuryhomes', 'acerojoaquintorr...",social,"['Sitevisit', 'Luxuryhomes', 'Steeljoaquintorr...",4228417,Turkey
2,adidas,adidas,adidas\n#ImpossibleIsNothing\nlinktr.ee/adidas,155061.90,HIM üì∏ @jharden13\n\n#HardenVol7 #adidasBasketb...,adidas\n#ImpossibleIsNothing\nlinktr.ee/adidas...,Adidas\n#Impossibleisnoting\nlinktr.ee/adidas ...,"['hardenvol7', 'adidasbasketball', 'impossible...",social,"['hardenvol7', 'adidasbasketball', 'impossible...",2041166,United Kingdom
3,airfrance,airfrance,Air France\n‚úàÔ∏è Welcome on board!\nPost your be...,12396.00,Getting ready for departure üòé\nWhich destinati...,Air France\n‚úàÔ∏è Welcome on board!\nPost your be...,Air France\n‚úàÔ∏è Welcome on board!\nPost your be...,"['airfrance', 'airplane', 'avgeek', 'aviation'...",social,"['airfrance', 'airplane', 'avgeek', 'aviation'...",11110475,Tanzania
4,amazon,amazon,Amazon\nRetail company\nCurrently manifesting ...,1851.95,"üìçOkinawa, Japan üìçMurano, Italy üìçMackinac Islan...",Amazon\nRetail company\nCurrently manifesting ...,Amazon\nRetail company\nCurrently manifesting ...,"['blackisremarkable', 'itsonprime', 'blackisre...",social,"['blackisremarkable', 'itsonprime', 'blackisre...",1932665,DR Congo
...,...,...,...,...,...,...,...,...,...,...,...,...
88,virginatlantic,virginatlantic,Virgin Atlantic\nWe‚Äôve always championed indiv...,7758.00,"Our iconic Vivienne Westwood uniforms, designe...",Virgin Atlantic\nWe‚Äôve always championed indiv...,Virgin Atlantic\nWe‚Äôve always championed indiv...,"['seetheworlddifferently', 'seetheworlddiffere...",social,"['seetheworlddifferently', 'seetheworlddiffere...",6308799,South Africa
89,volkswagen,volkswagen,Volkswagen\nCars\nWelcome to our official chan...,9510.10,World premiere of our new ID. 2all.\n\n#concep...,Volkswagen\nCars\nWelcome to our official chan...,Volkswagen\nCars\nWelcome to our official chan...,"['conceptcar', 'worldpremiere', 'vwid2all', 'v...",parenting_family,"['conceptcar', 'worldpremiere', 'vwid2all', 'v...",9416439,South Korea
90,wholesome_for.you,wholesome_for.you,wholesome memes\nüíù I try to make your relation...,744.25,"Tag someone ‚ù§Ô∏è\n-\n\n.\nDM for Credit\n.\n.,Ta...",wholesome memes\nüíù I try to make your relation...,wholesome memes\nüíù I try to make your relation...,[],social,[],1786934,Bangladesh
91,williamssonoma,williamssonoma,Williams Sonoma\nShopping & retail\nüì∑ Share yo...,4101.10,"Make these Chicken, Spinach and Gruy√®re Turnov...",Williams Sonoma\nShopping & retail\nüì∑ Share yo...,Williams Sonoma\nShopping & retail\nüì∑ Share yo...,"['weeknightdinner', 'makeahead', 'kidslunch', ...",social,"['weeknightdinner', 'makeahead', 'kidslunch', ...",7418292,United States
92,ysl,ysl,SAINT LAURENT\nThe official Saint Laurent Inst...,20570.70,Caren & Yanan - Summer 23‚Å£\nby Anthony Vaccare...,SAINT LAURENT\nThe official Saint Laurent Inst...,SAINT LAURENT\nThe official Saint Laurent Inst...,"['ysl', 'saintlaurent', 'yvessaintlaurent', 'y...",art_design,"['ysl', 'saintlaurent', 'yvessaintlaurent', 'y...",14515162,Tanzania

In [146]:
# create an ID column for the dataframe
df_co['ID_brand'] = range(1, len(df_co) + 1)

In [147]:
df_co.head()

,brand_name,brand_name.1,brand_description,brand_likes,brand_post_description,all_descriptions,descriptions_translated,hashtags,category,hashtags_translated,followers,location,ID_brand
0,abcnetwork,abcnetwork,ABC\nAmerica‚Äôs Network.\nabc.com,1871.40,Who will make Top 24!? Tune in to #AmericanIdo...,ABC\nAmerica‚Äôs Network.\nabc.com Who will make...,ABC\nAmerica‚Äôs Network.\nabc.com Who will make...,"['americanidol', 'americanidol', 'americanidol...",social,"['americanidol', 'americanidol', 'americanidol...",4172512,Pakistan,1
1,acerojoaquintorres,acerojoaquintorres,Joaquin Torres\nArchitectural designer\nA-cero...,1504.80,"Esta es, sin duda, una de las viviendas m√°s gr...",Joaquin Torres\nArchitectural designer\nA-cero...,Joaquin Torres\nArchitectural Designer\nSteel\...,"['sitevisit', 'luxuryhomes', 'acerojoaquintorr...",social,"['Sitevisit', 'Luxuryhomes', 'Steeljoaquintorr...",4228417,Turkey,2
2,adidas,adidas,adidas\n#ImpossibleIsNothing\nlinktr.ee/adidas,155061.90,HIM üì∏ @jharden13\n\n#HardenVol7 #adidasBasketb...,adidas\n#ImpossibleIsNothing\nlinktr.ee/adidas...,Adidas\n#Impossibleisnoting\nlinktr.ee/adidas ...,"['hardenvol7', 'adidasbasketball', 'impossible...",social,"['hardenvol7', 'adidasbasketball', 'impossible...",2041166,United Kingdom,3
3,airfrance,airfrance,Air France\n‚úàÔ∏è Welcome on board!\nPost your be...,12396.00,Getting ready for departure üòé\nWhich destinati...,Air France\n‚úàÔ∏è Welcome on board!\nPost your be...,Air France\n‚úàÔ∏è Welcome on board!\nPost your be...,"['airfrance', 'airplane', 'avgeek', 'aviation'...",social,"['airfrance', 'airplane', 'avgeek', 'aviation'...",11110475,Tanzania,4
4,amazon,amazon,Amazon\nRetail company\nCurrently manifesting ...,1851.95,"üìçOkinawa, Japan üìçMurano, Italy üìçMackinac Islan...",Amazon\nRetail company\nCurrently manifesting ...,Amazon\nRetail company\nCurrently manifesting ...,"['blackisremarkable', 'itsonprime', 'blackisre...",social,"['blackisremarkable', 'itsonprime', 'blackisre...",1932665,DR Congo,5

In [148]:
# Upload users (influencers) dataset
df_influ = pd.read_csv('influencers_df.csv')
df_influ

,ID,ID.1,user_Name,followers,user_Description,likes,post_Description,location,locations2,hashtags,post_Url,engagement_rate,hashtags_translated,all_descriptions,traducido,max_category,location3
0,1,1,0nlyfitgirls_,824122,‚≠ïÔ∏ènlyFitGirls\nBlogger\n12 years sharing the w...,26022.720,"@anabra7\n#OnlyFitGirls,@daniellebrandon7\n#On...",[],[],"['onlyfitgirls', 'onlyfitgirls', 'onlyfitgirls...","https://www.instagram.com/p/CqbVLmrjEKV/,https...",0.031576,"['onlyfitgirls', 'onlyfitgirls', 'onlyfitgirls...",‚≠ïÔ∏ènlyfitgirl blogger hare athlet photograph...,‚≠ïÔ∏ènlyfitgirl blogger 12 year share work athlet...,finance_investing,[]
1,2,2,100de100marifet,898694,OÃàznur Uslu\nüáπüá∑T√ºrkiye-üá´üá∑ Fransa\nYeni ve deta...,6380.100,Video‚Äômu g√∂renlerden ricam yoruma bir ‚ù§Ô∏è koyab...,[],[],"['ki≈ü', 'quiche']","https://www.instagram.com/p/ClWkdFID3TI/,https...",0.007099,"['ki≈ü', 'quiche']",oÃàznr l üáπüá∑t√ºrkiye-üá´üá∑ frana yeni detaylƒ± l tari...,oÃàznur uslu üáπüá∑t√ºrkiye-üá´üá∑ fransa yeni detaylƒ± v...,fitness_sport,[]
2,3,3,100montaditos,214440,ùü≠ùü¨ùü¨ ùó†ùó¢ùó°ùóßùóîùóóùóúùóßùó¢ùó¶\nDepende de ti c√≥mo te lo monte...,319.900,"¬øCu√°l es el tuyo?\n*Todos llevan kiko crushed,...",[],[],[],"https://www.instagram.com/p/Cqi3186NCvJ/,https...",0.001492,[],ùü≠ùü¨ùü¨ ùó†ùó¢ùó°ùóßùóîùóóùóúùóßùó¢ùó¶ depend c√≥mo mont üî• tiktok : 00m...,ùü≠ùü¨ùü¨ ùó†ùó¢ùó°ùóßùóîùóóùóúùóßùó¢ùó¶ Depend how Mont üî• Tiktok: 100mo...,social,[]
3,4,4,12storeez,893972,12 STOREEZ\nTienda de ropa\n–ö–æ–ª–ª–µ–∫—Ü–∏—è –¥–ª—è –º—É–∂—á...,7082.600,"–ú—ã —É–≤–µ—Ä–µ–Ω—ã: –≥–∞—Ä–¥–µ—Ä–æ–± ‚Äî —ç—Ç–æ –±–æ–ª—å—à–µ, —á–µ–º –ø—Ä–æ—Å—Ç–æ ...","['–†–æ—Å—Å–∏—è', '–†–æ—Å—Å–∏—è', 'Italia', 'France']",[],[],"https://www.instagram.com/p/CqxI42KMV1Y/,https...",0.007923,[],toreez tienda ropa –∫–æ–ª–ª–µ–∫—Ü–∏—è –º—É–∂—á–∏–Ω : @ toree...,12 Storeez Tienda Ropa Collection of men: @ 12...,parenting_family,"['–†–æ—Å—Å–∏—è', '–†–æ—Å—Å–∏—è', 'Italia', 'France']"
4,5,5,1gpmuthu,663592,GPMuthu 24 üîò\nArtist\nBiggboss S6\nCookuwithco...,127999.976,"@kuraishi_the_entertainer,‡Æö‡ÆÆ‡ÆØ‡Æ™‡ØÅ‡Æ∞‡ÆÆ‡Øç ‡ÆÆ‡Ææ‡Æ∞‡Æø‡ÆØ‡ÆÆ‡Øç‡ÆÆ‡Æ©‡Øç ...",['India'],[],[],"https://www.instagram.com/p/CqVM8-APGCs/,https...",0.192890,[],gpmth üîò artit biggbo 6 cookwithali bi enqiri...,gpmuthu 24 üîò artist biggboss s6 cookuwithcomal...,fashion,['India']
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2221,2222,2222,zubairatukhugov,51954,Zubaira Tukhugov\nUFC Fighter 19-4 Record\n‚Ä¢\n...,35503.232,–ù–µ—Ä–µ–∞–ª—å–Ω—ã–π –≤–∫—É—Å @gorillaenergy @gorillafightin...,[],[],"['–¥—É–±–∞–π', 'gorillaenergy', 'gorillafighting']","https://www.instagram.com/p/CqazvpjMM5l/,https...",0.683359,"['–¥—É–±–∞–π', 'gorillaenergy', 'gorillafighting']",zbaira tkhv fc fighter 9- record ‚Ä¢ –≤–æ–ø—Ä–æ—Å–∞–º —Å–æ...,Zubaira Tukhugov UFC Fighter 19-4 Record ‚Ä¢ Wri...,parenting_family,[]
2222,2223,2223,zubbymichael,5749589,zubby michael\nActor\nhttps://youtu.be/drTnOhf...,251222.500,Midnight cruise üî•GOD is real #ZM #A1 #doings #...,[],[],"['zm', 'a1', 'doings', 'nawedeyhere', 'blessup...","https://www.instagram.com/p/CqMJCMXjlCF/,https...",0.043694,"['zm', 'a1', 'doings', 'nawedeyhere', 'blessup...",zbbi michael actor http : //yot.be/drtnohfzafa...,zubbi michael actor http : //youtu.be/drtnohfz...,travel,[]
2223,2224,2224,zvezdegranda,408734,Zvezde Granda\nTV Programme\ngrand.nova.rs,28208.856,Sa kim to @voja.nedeljkovic obara ruke u Zvezd...,[],[],"['zvezdegranda', 'zvezdegranda']","https://www.instagram.com/p/CqV3wt4KAq-/,https...",0.069015,"['zvezdegranda', 'zvezdegranda']",zvezd granda tv programm grand.nova.r kim @ vo...,Star Granda TV Programm Grand.nova.r Kim @ voj...,social,[]
2224,2225,2225,zyzzmad,894950,Aziz Zyzz shavershian\nComunidad\n| motivation...,16446.000,"nan,Zyzz last vlog\n.\n.\nüëâ @zyzzmad Follow : ...",[],[],"['zyzzpose', 'zyzz', 'zyzzmotivation', 'zyzzle...","https://www.instagram.com/p/CoppL0cIqJm/,https...",0.018376,"['zyzzpose', 'zyzz', 'zyzzmotivation', 'zyzzle...",aziz zyzz haverhian nidad | motiv pot everi |...,aziz zyzz shavershian comunidad | motiv post e...,music,[]
2225,2226,2226,zzdaozz,804472,Dao N. Simasthien‚ú®\nDaoke 92üíü‚ôæ\nfreelance actr...,63443.316,‡∏ô‡∏≤‡∏ô‡∏°‡∏≤‡∏Å‡πÅ‡∏•‡πâ‡∏ß‡∏ó‡∏µ‡πà‡πÑ‡∏°‡πà‡πÑ‡∏î‡πâ‡πÉ‡∏ä‡πâ‡∏†‡∏≤‡∏©‡∏≤‡∏ç‡∏µ‡πà‡∏õ‡∏∏‡πà‡∏ô‡∏ó‡∏µ‡πà‡πÄ‡∏£‡∏µ‡∏¢‡∏ô‡∏°‡∏≤‡πÄ‡∏•‡∏¢...,[],['japan'],"['mcdaoke', 'tpopstageshowxthaifestivaljp', 't...","https://www.instagram.com/p/Cdk4RPsFXpK/,https...",0.078863,"['mcdaoke', 'tpopstageshowxthaifestivaljp', 't...",dao n. imathien‚ú® daok 9üíü‚ôæ freelanc actre mc # ...,DAO N. Simasthien‚ú® DAOK 92üíü‚ôæ Freelanc Actress ...,social,"[""'japan'""]"

In [149]:
#Solve problems with apostophre
df_influ['location3'] = df_influ['location3'].str.replace('"', '')

In [150]:
df_influ

,ID,ID.1,user_Name,followers,user_Description,likes,post_Description,location,locations2,hashtags,post_Url,engagement_rate,hashtags_translated,all_descriptions,traducido,max_category,location3
0,1,1,0nlyfitgirls_,824122,‚≠ïÔ∏ènlyFitGirls\nBlogger\n12 years sharing the w...,26022.720,"@anabra7\n#OnlyFitGirls,@daniellebrandon7\n#On...",[],[],"['onlyfitgirls', 'onlyfitgirls', 'onlyfitgirls...","https://www.instagram.com/p/CqbVLmrjEKV/,https...",0.031576,"['onlyfitgirls', 'onlyfitgirls', 'onlyfitgirls...",‚≠ïÔ∏ènlyfitgirl blogger hare athlet photograph...,‚≠ïÔ∏ènlyfitgirl blogger 12 year share work athlet...,finance_investing,[]
1,2,2,100de100marifet,898694,OÃàznur Uslu\nüáπüá∑T√ºrkiye-üá´üá∑ Fransa\nYeni ve deta...,6380.100,Video‚Äômu g√∂renlerden ricam yoruma bir ‚ù§Ô∏è koyab...,[],[],"['ki≈ü', 'quiche']","https://www.instagram.com/p/ClWkdFID3TI/,https...",0.007099,"['ki≈ü', 'quiche']",oÃàznr l üáπüá∑t√ºrkiye-üá´üá∑ frana yeni detaylƒ± l tari...,oÃàznur uslu üáπüá∑t√ºrkiye-üá´üá∑ fransa yeni detaylƒ± v...,fitness_sport,[]
2,3,3,100montaditos,214440,ùü≠ùü¨ùü¨ ùó†ùó¢ùó°ùóßùóîùóóùóúùóßùó¢ùó¶\nDepende de ti c√≥mo te lo monte...,319.900,"¬øCu√°l es el tuyo?\n*Todos llevan kiko crushed,...",[],[],[],"https://www.instagram.com/p/Cqi3186NCvJ/,https...",0.001492,[],ùü≠ùü¨ùü¨ ùó†ùó¢ùó°ùóßùóîùóóùóúùóßùó¢ùó¶ depend c√≥mo mont üî• tiktok : 00m...,ùü≠ùü¨ùü¨ ùó†ùó¢ùó°ùóßùóîùóóùóúùóßùó¢ùó¶ Depend how Mont üî• Tiktok: 100mo...,social,[]
3,4,4,12storeez,893972,12 STOREEZ\nTienda de ropa\n–ö–æ–ª–ª–µ–∫—Ü–∏—è –¥–ª—è –º—É–∂—á...,7082.600,"–ú—ã —É–≤–µ—Ä–µ–Ω—ã: –≥–∞—Ä–¥–µ—Ä–æ–± ‚Äî —ç—Ç–æ –±–æ–ª—å—à–µ, —á–µ–º –ø—Ä–æ—Å—Ç–æ ...","['–†–æ—Å—Å–∏—è', '–†–æ—Å—Å–∏—è', 'Italia', 'France']",[],[],"https://www.instagram.com/p/CqxI42KMV1Y/,https...",0.007923,[],toreez tienda ropa –∫–æ–ª–ª–µ–∫—Ü–∏—è –º—É–∂—á–∏–Ω : @ toree...,12 Storeez Tienda Ropa Collection of men: @ 12...,parenting_family,"['–†–æ—Å—Å–∏—è', '–†–æ—Å—Å–∏—è', 'Italia', 'France']"
4,5,5,1gpmuthu,663592,GPMuthu 24 üîò\nArtist\nBiggboss S6\nCookuwithco...,127999.976,"@kuraishi_the_entertainer,‡Æö‡ÆÆ‡ÆØ‡Æ™‡ØÅ‡Æ∞‡ÆÆ‡Øç ‡ÆÆ‡Ææ‡Æ∞‡Æø‡ÆØ‡ÆÆ‡Øç‡ÆÆ‡Æ©‡Øç ...",['India'],[],[],"https://www.instagram.com/p/CqVM8-APGCs/,https...",0.192890,[],gpmth üîò artit biggbo 6 cookwithali bi enqiri...,gpmuthu 24 üîò artist biggboss s6 cookuwithcomal...,fashion,['India']
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2221,2222,2222,zubairatukhugov,51954,Zubaira Tukhugov\nUFC Fighter 19-4 Record\n‚Ä¢\n...,35503.232,–ù–µ—Ä–µ–∞–ª—å–Ω—ã–π –≤–∫—É—Å @gorillaenergy @gorillafightin...,[],[],"['–¥—É–±–∞–π', 'gorillaenergy', 'gorillafighting']","https://www.instagram.com/p/CqazvpjMM5l/,https...",0.683359,"['–¥—É–±–∞–π', 'gorillaenergy', 'gorillafighting']",zbaira tkhv fc fighter 9- record ‚Ä¢ –≤–æ–ø—Ä–æ—Å–∞–º —Å–æ...,Zubaira Tukhugov UFC Fighter 19-4 Record ‚Ä¢ Wri...,parenting_family,[]
2222,2223,2223,zubbymichael,5749589,zubby michael\nActor\nhttps://youtu.be/drTnOhf...,251222.500,Midnight cruise üî•GOD is real #ZM #A1 #doings #...,[],[],"['zm', 'a1', 'doings', 'nawedeyhere', 'blessup...","https://www.instagram.com/p/CqMJCMXjlCF/,https...",0.043694,"['zm', 'a1', 'doings', 'nawedeyhere', 'blessup...",zbbi michael actor http : //yot.be/drtnohfzafa...,zubbi michael actor http : //youtu.be/drtnohfz...,travel,[]
2223,2224,2224,zvezdegranda,408734,Zvezde Granda\nTV Programme\ngrand.nova.rs,28208.856,Sa kim to @voja.nedeljkovic obara ruke u Zvezd...,[],[],"['zvezdegranda', 'zvezdegranda']","https://www.instagram.com/p/CqV3wt4KAq-/,https...",0.069015,"['zvezdegranda', 'zvezdegranda']",zvezd granda tv programm grand.nova.r kim @ vo...,Star Granda TV Programm Grand.nova.r Kim @ voj...,social,[]
2224,2225,2225,zyzzmad,894950,Aziz Zyzz shavershian\nComunidad\n| motivation...,16446.000,"nan,Zyzz last vlog\n.\n.\nüëâ @zyzzmad Follow : ...",[],[],"['zyzzpose', 'zyzz', 'zyzzmotivation', 'zyzzle...","https://www.instagram.com/p/CoppL0cIqJm/,https...",0.018376,"['zyzzpose', 'zyzz', 'zyzzmotivation', 'zyzzle...",aziz zyzz haverhian nidad | motiv pot everi |...,aziz zyzz shavershian comunidad | motiv post e...,music,[]
2225,2226,2226,zzdaozz,804472,Dao N. Simasthien‚ú®\nDaoke 92üíü‚ôæ\nfreelance actr...,63443.316,‡∏ô‡∏≤‡∏ô‡∏°‡∏≤‡∏Å‡πÅ‡∏•‡πâ‡∏ß‡∏ó‡∏µ‡πà‡πÑ‡∏°‡πà‡πÑ‡∏î‡πâ‡πÉ‡∏ä‡πâ‡∏†‡∏≤‡∏©‡∏≤‡∏ç‡∏µ‡πà‡∏õ‡∏∏‡πà‡∏ô‡∏ó‡∏µ‡πà‡πÄ‡∏£‡∏µ‡∏¢‡∏ô‡∏°‡∏≤‡πÄ‡∏•‡∏¢...,[],['japan'],"['mcdaoke', 'tpopstageshowxthaifestivaljp', 't...","https://www.instagram.com/p/Cdk4RPsFXpK/,https...",0.078863,"['mcdaoke', 'tpopstageshowxthaifestivaljp', 't...",dao n. imathien‚ú® daok 9üíü‚ôæ freelanc actre mc # ...,DAO N. Simasthien‚ú® DAOK 92üíü‚ôæ Freelanc Actress ...,social,['japan']

We will now merge both dataframes, so that we can have interactions between both the companies and the users.

In [151]:
df2_co = pd.concat([df_co]*len(df_influ), ignore_index=True)

In [152]:
df2_influ = pd.DataFrame(np.repeat(df_influ.values, len(df_co), axis=0))

In [153]:
# Concat both df
df = pd.concat([df2_influ, df2_co], axis=1)

In [154]:
df.head()

,0,1,2,3,4,5,6,7,8,9,...,brand_likes,brand_post_description,all_descriptions,descriptions_translated,hashtags,category,hashtags_translated,followers,location,ID_brand
0,1,1,0nlyfitgirls_,824122,‚≠ïÔ∏ènlyFitGirls\nBlogger\n12 years sharing the w...,26022.72,"@anabra7\n#OnlyFitGirls,@daniellebrandon7\n#On...",[],[],"['onlyfitgirls', 'onlyfitgirls', 'onlyfitgirls...",...,1871.40,Who will make Top 24!? Tune in to #AmericanIdo...,ABC\nAmerica‚Äôs Network.\nabc.com Who will make...,ABC\nAmerica‚Äôs Network.\nabc.com Who will make...,"['americanidol', 'americanidol', 'americanidol...",social,"['americanidol', 'americanidol', 'americanidol...",4172512,Pakistan,1
1,1,1,0nlyfitgirls_,824122,‚≠ïÔ∏ènlyFitGirls\nBlogger\n12 years sharing the w...,26022.72,"@anabra7\n#OnlyFitGirls,@daniellebrandon7\n#On...",[],[],"['onlyfitgirls', 'onlyfitgirls', 'onlyfitgirls...",...,1504.80,"Esta es, sin duda, una de las viviendas m√°s gr...",Joaquin Torres\nArchitectural designer\nA-cero...,Joaquin Torres\nArchitectural Designer\nSteel\...,"['sitevisit', 'luxuryhomes', 'acerojoaquintorr...",social,"['Sitevisit', 'Luxuryhomes', 'Steeljoaquintorr...",4228417,Turkey,2
2,1,1,0nlyfitgirls_,824122,‚≠ïÔ∏ènlyFitGirls\nBlogger\n12 years sharing the w...,26022.72,"@anabra7\n#OnlyFitGirls,@daniellebrandon7\n#On...",[],[],"['onlyfitgirls', 'onlyfitgirls', 'onlyfitgirls...",...,155061.90,HIM üì∏ @jharden13\n\n#HardenVol7 #adidasBasketb...,adidas\n#ImpossibleIsNothing\nlinktr.ee/adidas...,Adidas\n#Impossibleisnoting\nlinktr.ee/adidas ...,"['hardenvol7', 'adidasbasketball', 'impossible...",social,"['hardenvol7', 'adidasbasketball', 'impossible...",2041166,United Kingdom,3
3,1,1,0nlyfitgirls_,824122,‚≠ïÔ∏ènlyFitGirls\nBlogger\n12 years sharing the w...,26022.72,"@anabra7\n#OnlyFitGirls,@daniellebrandon7\n#On...",[],[],"['onlyfitgirls', 'onlyfitgirls', 'onlyfitgirls...",...,12396.00,Getting ready for departure üòé\nWhich destinati...,Air France\n‚úàÔ∏è Welcome on board!\nPost your be...,Air France\n‚úàÔ∏è Welcome on board!\nPost your be...,"['airfrance', 'airplane', 'avgeek', 'aviation'...",social,"['airfrance', 'airplane', 'avgeek', 'aviation'...",11110475,Tanzania,4
4,1,1,0nlyfitgirls_,824122,‚≠ïÔ∏ènlyFitGirls\nBlogger\n12 years sharing the w...,26022.72,"@anabra7\n#OnlyFitGirls,@daniellebrandon7\n#On...",[],[],"['onlyfitgirls', 'onlyfitgirls', 'onlyfitgirls...",...,1851.95,"üìçOkinawa, Japan üìçMurano, Italy üìçMackinac Islan...",Amazon\nRetail company\nCurrently manifesting ...,Amazon\nRetail company\nCurrently manifesting ...,"['blackisremarkable', 'itsonprime', 'blackisre...",social,"['blackisremarkable', 'itsonprime', 'blackisre...",1932665,DR Congo,5

In [155]:
df.columns

Index([                        0,                         1,
                               2,                         3,
                               4,                         5,
                               6,                         7,
                               8,                         9,
                              10,                        11,
                              12,                        13,
                              14,                        15,
                              16,              'brand_name',
                  'brand_name.1',       'brand_description',
                   'brand_likes',  'brand_post_description',
              'all_descriptions', 'descriptions_translated',
                      'hashtags',                'category',
           'hashtags_translated',               'followers',
                      'location',                'ID_brand'],
      dtype='object')

We have a lot of columns that we don't need to create our algorithm, so we will drop them from the database.

In [156]:
df = df.drop([1, 4, 6, 7, 8, 9, 13, 14, 'brand_name.1', 'brand_description', 'brand_post_description', 'all_descriptions', 'descriptions_translated', 'hashtags'], axis=1)

As we have losen the name of some columns, we will use this opportunity to rename all columns and follow the same structure.

In [157]:
df = df.rename(columns={0: 'user_id', 2: 'user_name', 3: 'user_followers', 5: 'user_likes_mean', 10: 'user_links', 11: 'user_eng_rate', 12: 'user_hashtags_en', 15: 'user_category', 16: 'user_country', 'brand_likes': 'brand_likes_mean', 'category': 'brand_category', 'hashtags_translated': 'brand_hashtags_en', 'followers': 'brand_followers', 'location': 'brand_country', 'ID_brand': 'brand_id'})

In [158]:
df.head()

,user_id,user_name,user_followers,user_likes_mean,user_links,user_eng_rate,user_hashtags_en,user_category,user_country,brand_name,brand_likes_mean,brand_category,brand_hashtags_en,brand_followers,brand_country,brand_id
0,1,0nlyfitgirls_,824122,26022.72,"https://www.instagram.com/p/CqbVLmrjEKV/,https...",0.031576,"['onlyfitgirls', 'onlyfitgirls', 'onlyfitgirls...",finance_investing,[],abcnetwork,1871.40,social,"['americanidol', 'americanidol', 'americanidol...",4172512,Pakistan,1
1,1,0nlyfitgirls_,824122,26022.72,"https://www.instagram.com/p/CqbVLmrjEKV/,https...",0.031576,"['onlyfitgirls', 'onlyfitgirls', 'onlyfitgirls...",finance_investing,[],acerojoaquintorres,1504.80,social,"['Sitevisit', 'Luxuryhomes', 'Steeljoaquintorr...",4228417,Turkey,2
2,1,0nlyfitgirls_,824122,26022.72,"https://www.instagram.com/p/CqbVLmrjEKV/,https...",0.031576,"['onlyfitgirls', 'onlyfitgirls', 'onlyfitgirls...",finance_investing,[],adidas,155061.90,social,"['hardenvol7', 'adidasbasketball', 'impossible...",2041166,United Kingdom,3
3,1,0nlyfitgirls_,824122,26022.72,"https://www.instagram.com/p/CqbVLmrjEKV/,https...",0.031576,"['onlyfitgirls', 'onlyfitgirls', 'onlyfitgirls...",finance_investing,[],airfrance,12396.00,social,"['airfrance', 'airplane', 'avgeek', 'aviation'...",11110475,Tanzania,4
4,1,0nlyfitgirls_,824122,26022.72,"https://www.instagram.com/p/CqbVLmrjEKV/,https...",0.031576,"['onlyfitgirls', 'onlyfitgirls', 'onlyfitgirls...",finance_investing,[],amazon,1851.95,social,"['blackisremarkable', 'itsonprime', 'blackisre...",1932665,DR Congo,5

Now, we will transform the string variable than need to be lists, remove the '' symbol and return a list of words.

In [159]:
df['user_hashtags_en'] = df['user_hashtags_en'].apply(lambda x: ast.literal_eval(x))
df['user_country'] = df['user_country'].apply(lambda x: ast.literal_eval(x))
df['brand_hashtags_en'] = df['brand_hashtags_en'].apply(lambda x: ast.literal_eval(x))

In [160]:
df

,user_id,user_name,user_followers,user_likes_mean,user_links,user_eng_rate,user_hashtags_en,user_category,user_country,brand_name,brand_likes_mean,brand_category,brand_hashtags_en,brand_followers,brand_country,brand_id
0,1,0nlyfitgirls_,824122,26022.72,"https://www.instagram.com/p/CqbVLmrjEKV/,https...",0.031576,"[onlyfitgirls, onlyfitgirls, onlyfitgirls, onl...",finance_investing,[],abcnetwork,1871.40,social,"[americanidol, americanidol, americanidol, the...",4172512,Pakistan,1
1,1,0nlyfitgirls_,824122,26022.72,"https://www.instagram.com/p/CqbVLmrjEKV/,https...",0.031576,"[onlyfitgirls, onlyfitgirls, onlyfitgirls, onl...",finance_investing,[],acerojoaquintorres,1504.80,social,"[Sitevisit, Luxuryhomes, Steeljoaquintorres, A...",4228417,Turkey,2
2,1,0nlyfitgirls_,824122,26022.72,"https://www.instagram.com/p/CqbVLmrjEKV/,https...",0.031576,"[onlyfitgirls, onlyfitgirls, onlyfitgirls, onl...",finance_investing,[],adidas,155061.90,social,"[hardenvol7, adidasbasketball, impossibleisnot...",2041166,United Kingdom,3
3,1,0nlyfitgirls_,824122,26022.72,"https://www.instagram.com/p/CqbVLmrjEKV/,https...",0.031576,"[onlyfitgirls, onlyfitgirls, onlyfitgirls, onl...",finance_investing,[],airfrance,12396.00,social,"[airfrance, airplane, avgeek, aviation, travel...",11110475,Tanzania,4
4,1,0nlyfitgirls_,824122,26022.72,"https://www.instagram.com/p/CqbVLmrjEKV/,https...",0.031576,"[onlyfitgirls, onlyfitgirls, onlyfitgirls, onl...",finance_investing,[],amazon,1851.95,social,"[blackisremarkable, itsonprime, blackisremarka...",1932665,DR Congo,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
207013,2226,zzdaozz,804472,63443.316,"https://www.instagram.com/p/Cdk4RPsFXpK/,https...",0.078863,"[mcdaoke, tpopstageshowxthaifestivaljp, thaife...",social,[japan],virginatlantic,7758.00,social,"[seetheworlddifferently, seetheworlddifferentl...",6308799,South Africa,89
207014,2226,zzdaozz,804472,63443.316,"https://www.instagram.com/p/Cdk4RPsFXpK/,https...",0.078863,"[mcdaoke, tpopstageshowxthaifestivaljp, thaife...",social,[japan],volkswagen,9510.10,parenting_family,"[conceptcar, worldpremiere, vwid2all, vwforthe...",9416439,South Korea,90
207015,2226,zzdaozz,804472,63443.316,"https://www.instagram.com/p/Cdk4RPsFXpK/,https...",0.078863,"[mcdaoke, tpopstageshowxthaifestivaljp, thaife...",social,[japan],wholesome_for.you,744.25,social,[],1786934,Bangladesh,91
207016,2226,zzdaozz,804472,63443.316,"https://www.instagram.com/p/Cdk4RPsFXpK/,https...",0.078863,"[mcdaoke, tpopstageshowxthaifestivaljp, thaife...",social,[japan],williamssonoma,4101.10,social,"[weeknightdinner, makeahead, kidslunch, sunday...",7418292,United States,92
207017,2226,zzdaozz,804472,63443.316,"https://www.instagram.com/p/Cdk4RPsFXpK/,https...",0.078863,"[mcdaoke, tpopstageshowxthaifestivaljp, thaife...",social,[japan],ysl,20570.70,art_design,"[ysl, saintlaurent, yvessaintlaurent, ysl, sai...",14515162,Tanzania,93

Calculate the different number of points (score) for each pair of user-company depending on the match of different variables.

In [161]:
points_hashtags = (df.apply(lambda row: len(set(row['user_hashtags_en']).intersection(set(row['brand_hashtags_en']))), axis=1))*2
points_cat = np.where((df['user_category'] == df['brand_category']), 10, 0)
points_country = (df.apply(lambda row: len(set(row['brand_country']).intersection(set(row['user_country']))), axis=1))*5
points_eng = df['user_eng_rate']/df['user_followers']
df['points_hashtags'] = points_hashtags
df['points_eng'] = points_eng
df['points_cat'] = points_cat
df['points_country'] = points_country
df['points'] = df['points_cat'] + df['points_country'] + df["points_hashtags"] + df['points_eng']

df = df.drop(['points_cat', 'points_country', 'points_hashtags', 'points_eng'], axis=1)

In [162]:
df

,user_id,user_name,user_followers,user_likes_mean,user_links,user_eng_rate,user_hashtags_en,user_category,user_country,brand_name,brand_likes_mean,brand_category,brand_hashtags_en,brand_followers,brand_country,brand_id,points
0,1,0nlyfitgirls_,824122,26022.72,"https://www.instagram.com/p/CqbVLmrjEKV/,https...",0.031576,"[onlyfitgirls, onlyfitgirls, onlyfitgirls, onl...",finance_investing,[],abcnetwork,1871.40,social,"[americanidol, americanidol, americanidol, the...",4172512,Pakistan,1,0.0
1,1,0nlyfitgirls_,824122,26022.72,"https://www.instagram.com/p/CqbVLmrjEKV/,https...",0.031576,"[onlyfitgirls, onlyfitgirls, onlyfitgirls, onl...",finance_investing,[],acerojoaquintorres,1504.80,social,"[Sitevisit, Luxuryhomes, Steeljoaquintorres, A...",4228417,Turkey,2,0.0
2,1,0nlyfitgirls_,824122,26022.72,"https://www.instagram.com/p/CqbVLmrjEKV/,https...",0.031576,"[onlyfitgirls, onlyfitgirls, onlyfitgirls, onl...",finance_investing,[],adidas,155061.90,social,"[hardenvol7, adidasbasketball, impossibleisnot...",2041166,United Kingdom,3,0.0
3,1,0nlyfitgirls_,824122,26022.72,"https://www.instagram.com/p/CqbVLmrjEKV/,https...",0.031576,"[onlyfitgirls, onlyfitgirls, onlyfitgirls, onl...",finance_investing,[],airfrance,12396.00,social,"[airfrance, airplane, avgeek, aviation, travel...",11110475,Tanzania,4,0.0
4,1,0nlyfitgirls_,824122,26022.72,"https://www.instagram.com/p/CqbVLmrjEKV/,https...",0.031576,"[onlyfitgirls, onlyfitgirls, onlyfitgirls, onl...",finance_investing,[],amazon,1851.95,social,"[blackisremarkable, itsonprime, blackisremarka...",1932665,DR Congo,5,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
207013,2226,zzdaozz,804472,63443.316,"https://www.instagram.com/p/Cdk4RPsFXpK/,https...",0.078863,"[mcdaoke, tpopstageshowxthaifestivaljp, thaife...",social,[japan],virginatlantic,7758.00,social,"[seetheworlddifferently, seetheworlddifferentl...",6308799,South Africa,89,10.0
207014,2226,zzdaozz,804472,63443.316,"https://www.instagram.com/p/Cdk4RPsFXpK/,https...",0.078863,"[mcdaoke, tpopstageshowxthaifestivaljp, thaife...",social,[japan],volkswagen,9510.10,parenting_family,"[conceptcar, worldpremiere, vwid2all, vwforthe...",9416439,South Korea,90,0.0
207015,2226,zzdaozz,804472,63443.316,"https://www.instagram.com/p/Cdk4RPsFXpK/,https...",0.078863,"[mcdaoke, tpopstageshowxthaifestivaljp, thaife...",social,[japan],wholesome_for.you,744.25,social,[],1786934,Bangladesh,91,10.0
207016,2226,zzdaozz,804472,63443.316,"https://www.instagram.com/p/Cdk4RPsFXpK/,https...",0.078863,"[mcdaoke, tpopstageshowxthaifestivaljp, thaife...",social,[japan],williamssonoma,4101.10,social,"[weeknightdinner, makeahead, kidslunch, sunday...",7418292,United States,92,10.0
207017,2226,zzdaozz,804472,63443.316,"https://www.instagram.com/p/Cdk4RPsFXpK/,https...",0.078863,"[mcdaoke, tpopstageshowxthaifestivaljp, thaife...",social,[japan],ysl,20570.70,art_design,"[ysl, saintlaurent, yvessaintlaurent, ysl, sai...",14515162,Tanzania,93,0.0

Check and change variables types.

In [163]:
df.dtypes

user_id               object
user_name             object
user_followers        object
user_likes_mean       object
user_links            object
user_eng_rate         object
user_hashtags_en      object
user_category         object
user_country          object
brand_name            object
brand_likes_mean     float64
brand_category        object
brand_hashtags_en     object
brand_followers        int64
brand_country         object
brand_id               int64
points                object
dtype: object

In [164]:
df['user_id'] = df['user_id'].astype(int)
df['user_name'] = df['user_name'].astype(str)
df['user_followers'] = df['user_followers'].astype(int)
df['user_likes_mean'] = df['user_likes_mean'].astype(float)
df['user_links'] = df['user_links'].astype(str)
df['user_eng_rate'] = df['user_eng_rate'].astype(float)
df['user_category'] = df['user_category'].astype(str)
df['brand_id'] = df['brand_id'].astype(int)
df['brand_name'] = df['brand_name'].astype(str)
df['brand_followers'] = df['brand_followers'].astype(int)
df['brand_likes_mean'] = df['brand_likes_mean'].astype(float)
df['brand_category'] = df['brand_category'].astype(str)
df['brand_country'] = df['brand_country'].astype(str)
df['points'] = df['points'].astype(float)
df.dtypes

user_id                int32
user_name             object
user_followers         int32
user_likes_mean      float64
user_links            object
user_eng_rate        float64
user_hashtags_en      object
user_category         object
user_country          object
brand_name            object
brand_likes_mean     float64
brand_category        object
brand_hashtags_en     object
brand_followers        int32
brand_country         object
brand_id               int32
points               float64
dtype: object

To fit the lightfm model, we will change the name of some columns to fit the model.

In [165]:
# Change the name of columns to fit the model.
df = df.rename(columns={"user_id": "itemID", "brand_id": "userID", "points": "rating"})

Check null values.

In [166]:
df.isnull().sum()

itemID               0
user_name            0
user_followers       0
user_likes_mean      0
user_links           0
user_eng_rate        0
user_hashtags_en     0
user_category        0
user_country         0
brand_name           0
brand_likes_mean     0
brand_category       0
brand_hashtags_en    0
brand_followers      0
brand_country        0
userID               0
rating               0
dtype: int64

The following dataframe will be used to train the algorithm

In [167]:
df

,itemID,user_name,user_followers,user_likes_mean,user_links,user_eng_rate,user_hashtags_en,user_category,user_country,brand_name,brand_likes_mean,brand_category,brand_hashtags_en,brand_followers,brand_country,userID,rating
0,1,0nlyfitgirls_,824122,26022.720,"https://www.instagram.com/p/CqbVLmrjEKV/,https...",0.031576,"[onlyfitgirls, onlyfitgirls, onlyfitgirls, onl...",finance_investing,[],abcnetwork,1871.40,social,"[americanidol, americanidol, americanidol, the...",4172512,Pakistan,1,3.831507e-08
1,1,0nlyfitgirls_,824122,26022.720,"https://www.instagram.com/p/CqbVLmrjEKV/,https...",0.031576,"[onlyfitgirls, onlyfitgirls, onlyfitgirls, onl...",finance_investing,[],acerojoaquintorres,1504.80,social,"[Sitevisit, Luxuryhomes, Steeljoaquintorres, A...",4228417,Turkey,2,3.831507e-08
2,1,0nlyfitgirls_,824122,26022.720,"https://www.instagram.com/p/CqbVLmrjEKV/,https...",0.031576,"[onlyfitgirls, onlyfitgirls, onlyfitgirls, onl...",finance_investing,[],adidas,155061.90,social,"[hardenvol7, adidasbasketball, impossibleisnot...",2041166,United Kingdom,3,3.831507e-08
3,1,0nlyfitgirls_,824122,26022.720,"https://www.instagram.com/p/CqbVLmrjEKV/,https...",0.031576,"[onlyfitgirls, onlyfitgirls, onlyfitgirls, onl...",finance_investing,[],airfrance,12396.00,social,"[airfrance, airplane, avgeek, aviation, travel...",11110475,Tanzania,4,3.831507e-08
4,1,0nlyfitgirls_,824122,26022.720,"https://www.instagram.com/p/CqbVLmrjEKV/,https...",0.031576,"[onlyfitgirls, onlyfitgirls, onlyfitgirls, onl...",finance_investing,[],amazon,1851.95,social,"[blackisremarkable, itsonprime, blackisremarka...",1932665,DR Congo,5,3.831507e-08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
207013,2226,zzdaozz,804472,63443.316,"https://www.instagram.com/p/Cdk4RPsFXpK/,https...",0.078863,"[mcdaoke, tpopstageshowxthaifestivaljp, thaife...",social,[japan],virginatlantic,7758.00,social,"[seetheworlddifferently, seetheworlddifferentl...",6308799,South Africa,89,1.000000e+01
207014,2226,zzdaozz,804472,63443.316,"https://www.instagram.com/p/Cdk4RPsFXpK/,https...",0.078863,"[mcdaoke, tpopstageshowxthaifestivaljp, thaife...",social,[japan],volkswagen,9510.10,parenting_family,"[conceptcar, worldpremiere, vwid2all, vwforthe...",9416439,South Korea,90,9.803113e-08
207015,2226,zzdaozz,804472,63443.316,"https://www.instagram.com/p/Cdk4RPsFXpK/,https...",0.078863,"[mcdaoke, tpopstageshowxthaifestivaljp, thaife...",social,[japan],wholesome_for.you,744.25,social,[],1786934,Bangladesh,91,1.000000e+01
207016,2226,zzdaozz,804472,63443.316,"https://www.instagram.com/p/Cdk4RPsFXpK/,https...",0.078863,"[mcdaoke, tpopstageshowxthaifestivaljp, thaife...",social,[japan],williamssonoma,4101.10,social,"[weeknightdinner, makeahead, kidslunch, sunday...",7418292,United States,92,1.000000e+01
207017,2226,zzdaozz,804472,63443.316,"https://www.instagram.com/p/Cdk4RPsFXpK/,https...",0.078863,"[mcdaoke, tpopstageshowxthaifestivaljp, thaife...",social,[japan],ysl,20570.70,art_design,"[ysl, saintlaurent, yvessaintlaurent, ysl, sai...",14515162,Tanzania,93,9.803113e-08

In [ ]:
df.to_csv('influencer_brand_df.csv', index=False)